### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kimthostrup** [laithsaid/nilan_mqtt#2]
Hi laithsaid,

Do you know if this will also work on the CTS700 controller board ?

Thanks
Kim

**Comment by laithsaid** [comment]
Hej Kim,

Not in the current version, but it can be modified to read CTS700. Do you have an idea on which registers you want to read?

mvh
Laith...

**Comment by kimthostrup** [comment]
Not yet, it is very early days in my Nilan data exfiltration days 😁

**Comment by laithsaid** [comment]
👍Let me and I will refactor the code to support it. On 15 Oct 2022, at 11.59, Kim Thostrup ***@***.***> wrote:﻿
Not yet, it is very early days in my Nilan data exfiltration days 😁

**Comment by kimthostrup** [comment]
> 👍Let me and I will refactor the code to support it. On 15 Oct 2022, at 11.59, Kim Thostrup ***@***.***> wrote:﻿ Not yet, it is very early days in my Nilan data exfiltration days 😁 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Thanks 😃

**Comment by laithsaid** [comment]
Kim, the code now support adding a json profile for any modbus device. So when you know which registers to read, we can just make a profile with the registers to read and it will work.
